management:
  endpoints:
    web:
      base-path: /api/actuator/

# Application info
info:
  name: 'Ideaportal'
  description: 'Ideaportal main site'
  version: '@project.version@'
  time: '@maven.build.timestamp@'
  app:
    encoding: '@project.build.sourceEncoding@'
    java:
      source: '@java.version@'
      target: '@java.version@'
server:
  port: 8084
  shutdown:
    graceful # see also spring.lifecycle.timeout-per-shutdown-phase=1m
spring:
  ai:
    openai:
      api-key: "UNIT_TEST_KEY"
    retry:
      max-attempts: 10  #Maximum number of retry attempts. 10
      backoff:
        initial-interval: 2  #Initial sleep duration for the exponential backoff policy. 2 sec
        multiplier: 5 #  Backoff interval multiplier.
        max-interval: 3 #  Maximum backoff duration. 3 min.
      on-client-errors: false #  If false, throw a NonTransientAiException, and do not attempt retry for 4xx client error codes  false
      exclude-on-http-codes: # List of HTTP status codes that should not trigger a retry (e.g. to throw NonTransientAiException). empty
      on-http-codes: #List of HTTP status codes that should trigger a retry (e.g. to throw TransientAiException). empty

  #mvc:
   # pathmatch:
    #  matching-strategy: ant-path-matcher
  main:
    allow-bean-definition-overriding: true
    banner-mode: "off"
    log-startup-info: true
  lifecycle:
    timeout-per-shutdown-phase: "30s"
  thymeleaf:
    check-template-location: false # to prevent warning
  codec:
    max-in-memory-size: 1024KB

  #database
  datasource:
    url: jdbc:mariadb://${DATABASE_ADDRESS}?useSSL=false&allowMultiQueries=true&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    username: ${MYSQL_USER:}
    password: ${MYSQL_PASSWORD:}
    continue-on-error: true # not working
  jpa:
    open-in-view: false #to prevent warning
    #show-sql: true
    #database-platform: org.hibernate.dialect.MySQL55Dialect
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
  #security:
  # user:
  #   name: ${ADMIN_USER:admin}
  #   password: ${ADMIN_PASSWORD:admin}

# job
org:
  jobrunr:
    background-job-server:
      enabled: true
    dashboard:
      enabled: true
      port: 8000 #the port on which to start the dashboard
    miscellaneous:
      allow-anonymous-data-usage: false #true sends the amount of succeeded jobs for marketing purposes

logging:
  level:
    com:
      zaxxer:
        hikari: OFF # suppress errors in log when DatabaseStartupValidator trying to connect to database
    #for ai log
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: DEBUG

  ai:
    ############################################################
    ###  openAI
    ############################################################
    # https://docs.spring.io/spring-ai/reference/api/chat/openai-chat.html
    # export SPRING_AI_OPENAI_API_KEY=<INSERT KEY HERE>
    openai:
      #api-key:

      #Name of the the OpenAI Chat model to use. You can select between models such as: gpt-4o, gpt-4o-mini, gpt-4-turbo, gpt-3.5-turbo
      #See the models page for more information. https://platform.openai.com/docs/models
      chat:
        options: {}
          #model: gpt-4o
        #model: llama-3.1-sonar-small-128k-online

        #The sampling temperature to use that controls the apparent creativity of generated completions.
        # Higher values will make output more random while lower values will make results more focused and deterministic.
        # It is not recommended to modify temperature and top_p for the same completions request as the interaction
        # of these two settings is difficult to predict.

        #temperature: 0.8

    ############################################################
    ###  ollama
    ############################################################
    # https://docs.spring.io/spring-ai/reference/api/chat/ollama-chat.html
    # models list https://github.com/ollama/ollama?tab=readme-ov-file#model-library
    ollama:
      chat:
        options:
          model: llama3.2:3b
          #temperature: 0:5
          #format: json
      #for remote
      #base-url: http://localhost:11434
      #base-url: http://192.168.1.149:11434



#----------------------------------------
web-config:
  website:
    siteLangs: "ru"
    siteLangInPath: false
    siteDomain: "ideology.ru"
    siteProtocol: "https"
    siteStaticStoragePath: "file:/mnt/sites/ideaportal/input"
    siteStoragePaths:
      - "file:/mnt/sites/ideaportal/input"
    siteInternalStoragePaths:
      - "file:/mnt/sites/ideaportal/mediainfo"
    createMetaOg: true
    createMetaForIcons: true
    useExternalUrlForImages: false
    keywords:
      key: "ideaportal.site.keywords"
    description:
      key: "ideaportal.site.description"
    siteTitle:
      key: "ideaportal.site.title"
    googleTagID: "G-FLJG5TXMQG"
    nav:
      - item:
        key: "ideaportal.menu.home"
        url: "index.htm"
      #- item:
      #  key: "ideaportal.menu.articles"
      #  url: "content.htm"
      - item:
        key: "ideaportal.menu.aphorisms"
        url: "#"
        subitems:
          - item:
            key: "ideaportal.menu.aphorisms.byauthor"
            url: "author/list"
          - item:
            key: "ideaportal.menu.aphorisms.bytopic"
            url: "topic/list"
          - item:
            key: "ideaportal.menu.aphorisms.proetcontra"
            url: "proetcontra/list"
          - item:
            key: "ideaportal.menu.aphorisms.favorite"
            url: "cite-favorite/list"
          #- item:
          #  key: "ideaportal.menu.aphorisms.search"
          #  url: "cite/list"
          - item:
            key: "ideaportal.menu.aphorisms.sources"
            url: "bibliography/list"
      - item:
        key: "ideaportal.menu.aphorisms.byauthor"
        url: "author/list"
      - item:
        key: "ideaportal.menu.aphorisms.bytopic"
        url: "topic/list"
      - item:
        key: "ideaportal.menu.aphorisms.proetcontra"
        url: "proetcontra/list"
      - item:
        key: "ideaportal.menu.about.project"
        url: "about.htm"
        subitems:
        #- item:
        #  key: "ideaportal.menu.about.project"
        #  url: "about.htm"
        - item:
          key: "ideaportal.menu.aphorisms.about"
          url: "about–∞phorisms.htm"
        - item:
          key: "ideaportal.menu.aphorisms.traditsii-filosofskoj-aforistiki"
          url: "razdely/filosofiya/filosofskaya-aforistika/19-traditsii-filosofskoj-aforistiki"
        #- item:
        #  key: "ideaportal.menu.links"
        #  url: "links.htm"

