logging:
  config: classpath:${LOGBACK:logback-local.xml}
  level:
    root: info
    com:
      dionext: debug

web-config:
  website:
    siteStaticStoragePath: "file:R:/doc/sites/ideaportal/input"
    siteStoragePaths:
      - "file:R:/doc/sites/ideaportal/input"
    siteInternalStoragePaths:
      - "file:R:/doc/sites/ideaportal/mediainfo"
