management:
  endpoints:
    web:
      base-path: /api/actuator/

# Application info
info:
  name: 'Ideaportal'
  description: 'Ideaportal main site'
  version: '@project.version@'
  time: '@maven.build.timestamp@'
  app:
    encoding: '@project.build.sourceEncoding@'
    java:
      source: '@java.version@'
      target: '@java.version@'
server:
  port: 8084
  shutdown:
    graceful # see also spring.lifecycle.timeout-per-shutdown-phase=1m
spring:
  #mvc:
   # pathmatch:
    #  matching-strategy: ant-path-matcher
  main:
    allow-bean-definition-overriding: true
    banner-mode: "off"
    log-startup-info: true
  lifecycle:
    timeout-per-shutdown-phase: "30s"
  thymeleaf:
    check-template-location: false # to prevent warning
  #database
  datasource:
    url: jdbc:mariadb://${DATABASE_ADDRESS}?useSSL=false&allowMultiQueries=true&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    username: ${MYSQL_USER:}
    password: ${MYSQL_PASSWORD:}
    continue-on-error: true # not working
  jpa:
    open-in-view: false #to prevent warning
    show-sql: true
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
  security:
    user:
      name: ${ADMIN_USER:admin}
      password: ${ADMIN_PASSWORD:admin}

logging:
  level:
    com:
      zaxxer:
        hikari: OFF # suppress errors in log when DatabaseStartupValidator trying to connect to database
#----------------------------------------
web-config:
  website:
    siteProtocol: "https"
  multiSites:
    ideaportal:
      siteLangs: "ru"
      siteLangInPath: false
      siteDomain: "ideology.ru"
      siteProtocol: "https"
      siteStaticStoragePath: "file:/mnt/sites/ideaportal/input"
      siteStoragePaths:
        - "file:/mnt/sites/ideaportal/input"
      siteInternalStoragePaths:
        - "file:/mnt/sites/ideaportal/mediainfo"
      createMetaOg: true
      createMetaForIcons: true
      useExternalUrlForImages: false
      keywords:
        key: "ideaportal.site.keywords"
      description:
        key: "ideaportal.site.description"
      siteTitle:
        key: "ideaportal.site.title"
      googleTagID: "G-FLJG5TXMQG"
      nav:
        - item:
          key: "ideaportal.menu.home"
          url: "index.htm"
        #- item:
        #  key: "ideaportal.menu.articles"
        #  url: "content.htm"
        - item:
          key: "ideaportal.menu.aphorisms"
          url: "#"
          subitems:
            - item:
              key: "ideaportal.menu.aphorisms.byauthor"
              url: "author/list"
            - item:
              key: "ideaportal.menu.aphorisms.bytopic"
              url: "topic/list"
            - item:
              key: "ideaportal.menu.aphorisms.proetcontra"
              url: "proetcontra/list"
            - item:
              key: "ideaportal.menu.aphorisms.favorite"
              url: "cite-favorite/list"
            #- item:
            #  key: "ideaportal.menu.aphorisms.search"
            #  url: "cite/list"
            - item:
              key: "ideaportal.menu.aphorisms.sources"
              url: "bibliography/list"
        - item:
          key: "ideaportal.menu.aphorisms.byauthor"
          url: "author/list"
        - item:
          key: "ideaportal.menu.aphorisms.bytopic"
          url: "topic/list"
        - item:
          key: "ideaportal.menu.aphorisms.proetcontra"
          url: "proetcontra/list"
        - item:
          key: "ideaportal.menu.about.project"
          url: "about.htm"
          subitems:
          #- item:
          #  key: "ideaportal.menu.about.project"
          #  url: "about.htm"
          - item:
            key: "ideaportal.menu.aphorisms.about"
            url: "about–∞phorisms.htm"
          - item:
            key: "ideaportal.menu.aphorisms.traditsii-filosofskoj-aforistiki"
            url: "razdely/filosofiya/filosofskaya-aforistika/19-traditsii-filosofskoj-aforistiki"
          #- item:
          #  key: "ideaportal.menu.links"
          #  url: "links.htm"

